config_name: base_ssdu,k=1
description: "base config, k=1"

n_layers: 5
k_iters: 1
epochs: 30

dataset_name: modl_dataset_ssdu
dataset_params:
  dataset_path: 'processedData/fastMRI.h5'
  sigma: 0.00001
val_data: False
batch_size: 1 

model_name: base_ssdu

restore_weights: False #False, best, inter, final
restore_path: 

loss_name: L1L2
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True