config_name: base_unet,k=10
description: "base config, k=10. Restore weights from <base_unet,k=10>"

n_layers: 5
k_iters: 1
epochs: 50

dataset_name: modl_dataset
dataset_params:
  dataset_path: 'processedData/fastMRI_2_cart.h5'
  sigma: 0.01
val_data: False
batch_size: 1

model_name: base_unet

restore_weights: False #False, best, inter, final
restore_path: 'workspace/base_unet,k=10/checkpoints/'

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True