config_name: base_ssdu,k=10
description: "base config, k=10. Restore weights from <base_ssdu,k=10>"

n_layers: 5
k_iters: 10
epochs: 30

dataset_name: modl_dataset_ssdu
dataset_params:
  dataset_path: 'processedData/fastMRI.h5'
  sigma: 0.00001
val_data: False
batch_size: 1

model_name: base_ssdu

restore_weights: False #False, best, inter, final
restore_path: 'workspace/base_ssdu,k=10/checkpoints/'

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True